### ISSUE TITLE
Update for LSP 3.0

### ISSUE THREAD

**Issue by jonathandturner** [gluon-lang/languageserver-types#10]
There are some new features in the new LSP.  We may want to update this crate to take advantage of them

https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

Namely, you can now:

* Work with external commands
* Have experimental features
* Register and unregister capabilities

Seems like it's structurally compatible with LSP 2.0, so it'd mostly be adding new fields.

**Comment by Marwes** [comment]
Was a while since I needed to do anything with a language server so this fell of my mind. Don't think I will need this myself for a while yet but I can look into it this weekend probably.
