### ISSUE TITLE
Update to Serde 1.0

### ISSUE THREAD

**Issue by jonathandturner** [gluon-lang/languageserver-types#11]
Serde 1.0 is now available, and since it's the LTS version we should probably bump to that

**Comment by Marwes** [comment]
Should be an easy upgrade. A bit busy at the moment but I will look into it over the weekend.

**Comment by Marwes** [comment]
Started upgrading to 1.0 but its currently blocked on https://github.com/servo/rust-url/pull/296

**Comment by dtolnay** [comment]
A Serde 1.0 compatible url_serde 0.2 has been released.
