### ISSUE TITLE
0.25 version does not contain changes from #44

### ISSUE THREAD

**Issue by Xanewok** [gluon-lang/languageserver-types#45]
It seems that 0.25 was published after the changes, but after inspecting the downloaded source files, it seems that the changes didn't make it (RegisterCapability is still a Notification).

**Comment by Marwes** [comment]
I may have forgotten or failed git pull before publishing that, did it kinda hap-hazardly since I were short on time, sorry! It should be good now (published 0.26 yanked 0.25)

**Comment by Xanewok** [comment]
No worries, thanks for such a quick response! 0.26 does indeed have the change mentioned.
