### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by bruno-medeiros** [gluon-lang/languageserver-types#5]
Heya, I wanted to publish RustLSP to Crates.io, but it requires publishing languageserver-types too.

You okay with publishing it? I could also publish it myself, if you'd prefer that. Dunno how easy it is to setup permissions to multiple people on Crates.io.

Also, should we keep it at version 0.6.0, or start off with 1.0.0 already? A case is made [here](https://medium.com/javascript-scene/software-versions-are-broken-3d2dc0da0783#.49tkvfk9z) for starting off at 1.0.0 quite early (even if still beta), in order to make SemVer work better. (although that likely won't be much of an issue for languageserver-types_

**Comment by Marwes** [comment]
The crate is already on crates.io https://crates.io/crates/languageserver-types. I actually thought I added you as an owner to it but I guess I hadn't. Want me to add you as an owner then?

> Also, should we keep it at version 0.6.0, or start off with 1.0.0 already? A case is made here for starting off at 1.0.0 quite early (even if still beta), in order to make SemVer work better. (although that likely won't be much of an issue for languageserver-types_

I think its fair to jump up to 1.x since the protocol itself should be stable. It seems like the protocol itself is actually at version 2.x so maybe we could even jump to 2.0 to closer match the protocol itself? https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

**Comment by bruno-medeiros** [comment]
ah, it's already published, didn't notice! Just a matter of updating then. And maybe bumping to 1.0.0.

**Comment by bruno-medeiros** [comment]
> The crate is already on crates.io https://crates.io/crates/languageserver-types. I actually thought I added you as an owner to it but I guess I hadn't. Want me to add you as an owner then?

Yes please! 👍 

> I think its fair to jump up to 1.x since the protocol itself should be stable. It seems like the protocol itself is actually at version 2.x so maybe we could even jump to 2.0 to closer match the protocol itself? https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

Nah, I don't think there should be any relation with the version number of languageserver-types and the protocol itself, so that we could be fully SemVer compliant. For example, suppose we wanted to make some incompatible API change in a constructor, this would require bumping the Major number, and yet the LSP protocol version would remain the same. It might be unlikely, but as a matter of principle, I don't think it's the right way to do it. (again that article elaborates a bit more why)

**Comment by Marwes** [comment]
Fair enough.

You should be added as an owner now.

**Comment by bruno-medeiros** [comment]
done, works.
