### ISSUE TITLE
Support Diagnostic.relatedInformation (LSP 3.7)

### ISSUE THREAD

**Issue by Xanewok** [gluon-lang/languageserver-types#55]
Changelog: https://microsoft.github.io/language-server-protocol/specification#version_3_7_0

LSP 3.7 introduced:
```ts
interface Diagnostic {
    ...

    /**
     * An array of related diagnostic information, e.g. when symbol-names within
     * a scope collide all definitions can be marked via this property.
     */
    relatedInformation?: DiagnosticRelatedInformation[];
}
```
and appropriately:
```ts
/**
 * Represents a related message and source code location for a diagnostic. This should be
 * used to point to code locations that cause or related to a diagnostics, e.g when duplicating
 * a symbol in a scope.
 */
export interface DiagnosticRelatedInformation {
	/**
	 * The location of this related diagnostic information.
	 */
	location: Location;

	/**
	 * The message of this related diagnostic information.
	 */
	message: string;
}
```

This can deprecate and replace temporary [`group`](https://github.com/gluon-lang/languageserver-types/blob/master/src/lib.rs#L141) property that aimed to solve this particular problem

**Comment by Marwes** [comment]
Just saw that a few days ago but haven't gotten around it it yet. We should also add a sentence to the readme that states that the library is (supposed to be) compatible with LSP 3.7
