### ISSUE TITLE
Consider adding `Request::Params: Deserialize` bound

### ISSUE THREAD

**Issue by matklad** [gluon-lang/languageserver-types#70]
Hi!

I have not thought out implications of this completely, but it might be useful to change the definition of `Request` to 

```rust
pub trait Request {
    type Params: DeserializeOwned;
    type Result: Serialize;
    const METHOD: &'static str;
}
```

That'd allow to write generic dispatch code using only `R: Request` bound. It is possible today by adding bounds `where R::Params: DeserializeOwned` on the call site, and thus not having the bounds upstream is more general. However in practice I think all params and results (even custom ones) are always serializable?

**Comment by matklad** [comment]
>However in practice I think all params and results (even custom ones) are always serializable?

Hm, actually if you are wring only a half of the protocol, than some things might be only serialize, and some things might be only deserialize. With this in mind, I think it's ok to make the client to supply the bounds.

**Comment by Marwes** [comment]
For all the types provided by this crate then params are always deserializeable and results are serializable. The main reason for this being omitted is that I like to be conservative with adding bounds and the place where I use this outside of the crate are in another abstraction so I never needed to deal with repeating the bounds. So I am not really against making this change at least.

**Comment by matklad** [comment]
I've actually tried to define my own extension trait, and turns out that, b/c my server is multithreaded, I needed `: Send + 'static` bounds as well:

https://github.com/matklad/libsyntax2/blob/46e4232cc69bc2e003dc8a14e604119bb36e9f9f/crates/server/src/req.rs#L10-L24

That is, even if upstream has `Ser/De`, I'll still would need my trait for Send...
