### ISSUE TITLE
Bump support for LSP 3.13.0

### ISSUE THREAD

**Issue by kjeremy** [gluon-lang/languageserver-types#76]
3.13.0 was released on 9/11/2018.

**Comment by Marwes** [comment]
Change log at https://microsoft.github.io/language-server-protocol/specification#version_3_13_0

**Comment by kjeremy** [comment]
I'm working my way up to 3.13.0 starting at #78

**Comment by kjeremy** [comment]
Ok I have everything else queued up locally. It builds on #78 so as soon as that looks good I can push the rest.
